<?php
/**
 * DocumentsReportPdf
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentsReportPdf Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsReportPdf implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DocumentsReportPdf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'document_date_month' => 'int',
        'document_date_year' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'document_date_month' => null,
        'document_date_year' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_date_month' => 'document_date_month',
        'document_date_year' => 'document_date_year'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_date_month' => 'setDocumentDateMonth',
        'document_date_year' => 'setDocumentDateYear'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_date_month' => 'getDocumentDateMonth',
        'document_date_year' => 'getDocumentDateYear'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['document_date_month'] = isset($data['document_date_month']) ? $data['document_date_month'] : null;
        $this->container['document_date_year'] = isset($data['document_date_year']) ? $data['document_date_year'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['document_date_month'] === null) {
            $invalidProperties[] = "'document_date_month' can't be null";
        }
        if (($this->container['document_date_month'] > 12)) {
            $invalidProperties[] = "invalid value for 'document_date_month', must be smaller than or equal to 12.";
        }

        if (($this->container['document_date_month'] < 1)) {
            $invalidProperties[] = "invalid value for 'document_date_month', must be bigger than or equal to 1.";
        }

        if ($this->container['document_date_year'] === null) {
            $invalidProperties[] = "'document_date_year' can't be null";
        }
        if (($this->container['document_date_year'] < 1990)) {
            $invalidProperties[] = "invalid value for 'document_date_year', must be bigger than or equal to 1990.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_date_month
     *
     * @return int
     */
    public function getDocumentDateMonth()
    {
        return $this->container['document_date_month'];
    }

    /**
     * Sets document_date_month
     *
     * @param int $document_date_month document_date_month
     *
     * @return $this
     */
    public function setDocumentDateMonth($document_date_month)
    {

        if (($document_date_month > 12)) {
            throw new \InvalidArgumentException('invalid value for $document_date_month when calling DocumentsReportPdf., must be smaller than or equal to 12.');
        }
        if (($document_date_month < 1)) {
            throw new \InvalidArgumentException('invalid value for $document_date_month when calling DocumentsReportPdf., must be bigger than or equal to 1.');
        }

        $this->container['document_date_month'] = $document_date_month;

        return $this;
    }

    /**
     * Gets document_date_year
     *
     * @return int
     */
    public function getDocumentDateYear()
    {
        return $this->container['document_date_year'];
    }

    /**
     * Sets document_date_year
     *
     * @param int $document_date_year document_date_year
     *
     * @return $this
     */
    public function setDocumentDateYear($document_date_year)
    {

        if (($document_date_year < 1990)) {
            throw new \InvalidArgumentException('invalid value for $document_date_year when calling DocumentsReportPdf., must be bigger than or equal to 1990.');
        }

        $this->container['document_date_year'] = $document_date_year;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


