<?php
/**
 * OrderSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderSettings Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderSettings implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'percentage_added_to_delivery' => 'int',
        'automatically_generate_and_finalise_fiscal' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'percentage_added_to_delivery' => null,
        'automatically_generate_and_finalise_fiscal' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'percentage_added_to_delivery' => 'percentage_added_to_delivery',
        'automatically_generate_and_finalise_fiscal' => 'automatically_generate_and_finalise_fiscal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'percentage_added_to_delivery' => 'setPercentageAddedToDelivery',
        'automatically_generate_and_finalise_fiscal' => 'setAutomaticallyGenerateAndFinaliseFiscal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'percentage_added_to_delivery' => 'getPercentageAddedToDelivery',
        'automatically_generate_and_finalise_fiscal' => 'getAutomaticallyGenerateAndFinaliseFiscal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['percentage_added_to_delivery'] = isset($data['percentage_added_to_delivery']) ? $data['percentage_added_to_delivery'] : null;
        $this->container['automatically_generate_and_finalise_fiscal'] = isset($data['automatically_generate_and_finalise_fiscal']) ? $data['automatically_generate_and_finalise_fiscal'] : false;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['percentage_added_to_delivery']) && ($this->container['percentage_added_to_delivery'] > 5000)) {
            $invalidProperties[] = "invalid value for 'percentage_added_to_delivery', must be smaller than or equal to 5000.";
        }

        if (!is_null($this->container['percentage_added_to_delivery']) && ($this->container['percentage_added_to_delivery'] < 0)) {
            $invalidProperties[] = "invalid value for 'percentage_added_to_delivery', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets percentage_added_to_delivery
     *
     * @return int
     */
    public function getPercentageAddedToDelivery()
    {
        return $this->container['percentage_added_to_delivery'];
    }

    /**
     * Sets percentage_added_to_delivery
     *
     * @param int $percentage_added_to_delivery Procentaj adăugat la prețul articolelor dacă se selectează livrare
     *
     * @return $this
     */
    public function setPercentageAddedToDelivery($percentage_added_to_delivery)
    {

        if (!is_null($percentage_added_to_delivery) && ($percentage_added_to_delivery > 5000)) {
            throw new \InvalidArgumentException('invalid value for $percentage_added_to_delivery when calling OrderSettings., must be smaller than or equal to 5000.');
        }
        if (!is_null($percentage_added_to_delivery) && ($percentage_added_to_delivery < 0)) {
            throw new \InvalidArgumentException('invalid value for $percentage_added_to_delivery when calling OrderSettings., must be bigger than or equal to 0.');
        }

        $this->container['percentage_added_to_delivery'] = $percentage_added_to_delivery;

        return $this;
    }

    /**
     * Gets automatically_generate_and_finalise_fiscal
     *
     * @return bool
     */
    public function getAutomaticallyGenerateAndFinaliseFiscal()
    {
        return $this->container['automatically_generate_and_finalise_fiscal'];
    }

    /**
     * Sets automatically_generate_and_finalise_fiscal
     *
     * @param bool $automatically_generate_and_finalise_fiscal Generează și finalizează automat facturi fiscale din comenzile plasate de către parteneri care au conexiune, dacă există produsele în stoc
     *
     * @return $this
     */
    public function setAutomaticallyGenerateAndFinaliseFiscal($automatically_generate_and_finalise_fiscal)
    {
        $this->container['automatically_generate_and_finalise_fiscal'] = $automatically_generate_and_finalise_fiscal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


