<?php
/**
 * CompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyTest Class Doc Comment
 *
 * @category    Class
 * @description Company(id, user, country, region, city, address, referral, personal_representative, name, logo, site_logo, pays_vat, vat_id, vat_intra, vat_at_income, reg_com, social_capital, email, website, phone, uuid, created, modules, trusted, type, caen)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Company"
     */
    public function testCompany()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "pays_vat"
     */
    public function testPropertyPaysVat()
    {
    }

    /**
     * Test attribute "vat_id"
     */
    public function testPropertyVatId()
    {
    }

    /**
     * Test attribute "vat_intra"
     */
    public function testPropertyVatIntra()
    {
    }

    /**
     * Test attribute "vat_at_income"
     */
    public function testPropertyVatAtIncome()
    {
    }

    /**
     * Test attribute "reg_com"
     */
    public function testPropertyRegCom()
    {
    }

    /**
     * Test attribute "social_capital"
     */
    public function testPropertySocialCapital()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "enabled_modules"
     */
    public function testPropertyEnabledModules()
    {
    }

    /**
     * Test attribute "modules"
     */
    public function testPropertyModules()
    {
    }

    /**
     * Test attribute "site_logo"
     */
    public function testPropertySiteLogo()
    {
    }

    /**
     * Test attribute "personal_representative"
     */
    public function testPropertyPersonalRepresentative()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "caen"
     */
    public function testPropertyCaen()
    {
    }

    /**
     * Test attribute "storage"
     */
    public function testPropertyStorage()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email_alias"
     */
    public function testPropertyEmailAlias()
    {
    }
}
