<?php
/**
 * EmployeeDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmployeeDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description EmployeeDetails(id, company, country, region, city, address, employee, citizenship, date_of_birth, job_title, identity_document, id_number, extra, work_approval, approval_start, approval_end)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployeeDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmployeeDetails"
     */
    public function testEmployeeDetails()
    {
    }

    /**
     * Test attribute "employee"
     */
    public function testPropertyEmployee()
    {
    }

    /**
     * Test attribute "citizenship"
     */
    public function testPropertyCitizenship()
    {
    }

    /**
     * Test attribute "identity_document"
     */
    public function testPropertyIdentityDocument()
    {
    }

    /**
     * Test attribute "id_number"
     */
    public function testPropertyIdNumber()
    {
    }

    /**
     * Test attribute "extra"
     */
    public function testPropertyExtra()
    {
    }

    /**
     * Test attribute "work_approval"
     */
    public function testPropertyWorkApproval()
    {
    }

    /**
     * Test attribute "approval_start"
     */
    public function testPropertyApprovalStart()
    {
    }

    /**
     * Test attribute "approval_end"
     */
    public function testPropertyApprovalEnd()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "cnp_data"
     */
    public function testPropertyCnpData()
    {
    }
}
