<?php
/**
 * EmploymentContractRevisionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmploymentContractRevisionTest Class Doc Comment
 *
 * @category    Class
 * @description EmploymentContract(id, company, employee, contract_number, contract_date, work_start, cod_cor, details, work_end, end_date_exception, contract_type, full_time, contract_time, shift_type, hour_split, working_hours, extra, status, contract_ended, from_date, revision, revision_date, salary, uuid, document)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmploymentContractRevisionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmploymentContractRevision"
     */
    public function testEmploymentContractRevision()
    {
    }

    /**
     * Test attribute "work_start"
     */
    public function testPropertyWorkStart()
    {
    }

    /**
     * Test attribute "cod_cor"
     */
    public function testPropertyCodCor()
    {
    }

    /**
     * Test attribute "work_end"
     */
    public function testPropertyWorkEnd()
    {
    }

    /**
     * Test attribute "end_date_exception"
     */
    public function testPropertyEndDateException()
    {
    }

    /**
     * Test attribute "contract_type"
     */
    public function testPropertyContractType()
    {
    }

    /**
     * Test attribute "full_time"
     */
    public function testPropertyFullTime()
    {
    }

    /**
     * Test attribute "contract_time"
     */
    public function testPropertyContractTime()
    {
    }

    /**
     * Test attribute "shift_type"
     */
    public function testPropertyShiftType()
    {
    }

    /**
     * Test attribute "hour_split"
     */
    public function testPropertyHourSplit()
    {
    }

    /**
     * Test attribute "working_hours"
     */
    public function testPropertyWorkingHours()
    {
    }

    /**
     * Test attribute "extra"
     */
    public function testPropertyExtra()
    {
    }

    /**
     * Test attribute "from_date"
     */
    public function testPropertyFromDate()
    {
    }

    /**
     * Test attribute "salary"
     */
    public function testPropertySalary()
    {
    }
}
