<?php
/**
 * OfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OfferTest Class Doc Comment
 *
 * @category    Class
 * @description Offer(id, created_at, modified_at, created_by, modified_by, snapshot, company, partner, currency, number, date, due_date, uuid, type, markup, discount_general, has_discount, subtotal, subtotal_currency, tax_value, tax_value_currency, total, total_currency, discounted_total, discounted_total_currency, exchange_rate, accepted, accepted_date, sent, sent_date)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Offer"
     */
    public function testOffer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "partner"
     */
    public function testPropertyPartner()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "discount_general"
     */
    public function testPropertyDiscountGeneral()
    {
    }

    /**
     * Test attribute "has_discount"
     */
    public function testPropertyHasDiscount()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "subtotal_currency"
     */
    public function testPropertySubtotalCurrency()
    {
    }

    /**
     * Test attribute "tax_value"
     */
    public function testPropertyTaxValue()
    {
    }

    /**
     * Test attribute "tax_value_currency"
     */
    public function testPropertyTaxValueCurrency()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "total_currency"
     */
    public function testPropertyTotalCurrency()
    {
    }

    /**
     * Test attribute "discounted_total"
     */
    public function testPropertyDiscountedTotal()
    {
    }

    /**
     * Test attribute "discounted_total_currency"
     */
    public function testPropertyDiscountedTotalCurrency()
    {
    }

    /**
     * Test attribute "exchange_rate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "accepted"
     */
    public function testPropertyAccepted()
    {
    }

    /**
     * Test attribute "accepted_date"
     */
    public function testPropertyAcceptedDate()
    {
    }

    /**
     * Test attribute "sent"
     */
    public function testPropertySent()
    {
    }

    /**
     * Test attribute "sent_date"
     */
    public function testPropertySentDate()
    {
    }

    /**
     * Test attribute "markup"
     */
    public function testPropertyMarkup()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "show_totals"
     */
    public function testPropertyShowTotals()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
