<?php
/**
 * ProjectTaskUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProjectTaskUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectTask(id, company, project, task_list, status_workflow, on_complete, machine, name, description, date, priority, billable, price, estimate, duration, position, subtasks, ready, can_be_closed, completed_at, created_at, added_by)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectTaskUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectTaskUpdate"
     */
    public function testProjectTaskUpdate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "status_workflow"
     */
    public function testPropertyStatusWorkflow()
    {
    }

    /**
     * Test attribute "billable"
     */
    public function testPropertyBillable()
    {
    }

    /**
     * Test attribute "assigned_to"
     */
    public function testPropertyAssignedTo()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "estimate"
     */
    public function testPropertyEstimate()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "depends_on"
     */
    public function testPropertyDependsOn()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "task_list"
     */
    public function testPropertyTaskList()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "subtasks"
     */
    public function testPropertySubtasks()
    {
    }

    /**
     * Test attribute "added_by"
     */
    public function testPropertyAddedBy()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "completed_at"
     */
    public function testPropertyCompletedAt()
    {
    }

    /**
     * Test attribute "ready"
     */
    public function testPropertyReady()
    {
    }

    /**
     * Test attribute "can_be_closed"
     */
    public function testPropertyCanBeClosed()
    {
    }

    /**
     * Test attribute "time_consumptions"
     */
    public function testPropertyTimeConsumptions()
    {
    }

    /**
     * Test attribute "on_complete"
     */
    public function testPropertyOnComplete()
    {
    }

    /**
     * Test attribute "status_colour"
     */
    public function testPropertyStatusColour()
    {
    }

    /**
     * Test attribute "machine"
     */
    public function testPropertyMachine()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }
}
