<?php
/**
 * PublicDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PublicDataTest Class Doc Comment
 *
 * @category    Class
 * @description PublicData(id, created_at, modified_at, company, user, identifier, cemetery, name, dob, dod, short_description, description)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PublicDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PublicData"
     */
    public function testPublicData()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {
    }

    /**
     * Test attribute "dod"
     */
    public function testPropertyDod()
    {
    }

    /**
     * Test attribute "age"
     */
    public function testPropertyAge()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "public_url"
     */
    public function testPropertyPublicUrl()
    {
    }

    /**
     * Test attribute "photos"
     */
    public function testPropertyPhotos()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "cemetery"
     */
    public function testPropertyCemetery()
    {
    }
}
