<?php
/**
 * DatasetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DatasetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DatasetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for datasetCityList
     *
     * .
     *
     */
    public function testDatasetCityList()
    {
    }

    /**
     * Test case for datasetCompanyInfoRead
     *
     * .
     *
     */
    public function testDatasetCompanyInfoRead()
    {
    }

    /**
     * Test case for datasetCountryList
     *
     * .
     *
     */
    public function testDatasetCountryList()
    {
    }

    /**
     * Test case for datasetCurrencyList
     *
     * .
     *
     */
    public function testDatasetCurrencyList()
    {
    }

    /**
     * Test case for datasetDeviceCreate
     *
     * .
     *
     */
    public function testDatasetDeviceCreate()
    {
    }

    /**
     * Test case for datasetExchangeRatesRead
     *
     * .
     *
     */
    public function testDatasetExchangeRatesRead()
    {
    }

    /**
     * Test case for datasetGeneratePdfList
     *
     * .
     *
     */
    public function testDatasetGeneratePdfList()
    {
    }

    /**
     * Test case for datasetGeneratePdfUpdate
     *
     * .
     *
     */
    public function testDatasetGeneratePdfUpdate()
    {
    }

    /**
     * Test case for datasetLanguageList
     *
     * .
     *
     */
    public function testDatasetLanguageList()
    {
    }

    /**
     * Test case for datasetMeasurementUnitList
     *
     * .
     *
     */
    public function testDatasetMeasurementUnitList()
    {
    }

    /**
     * Test case for datasetNotificationClassesList
     *
     * .
     *
     */
    public function testDatasetNotificationClassesList()
    {
    }

    /**
     * Test case for datasetNotificationModulesList
     *
     * .
     *
     */
    public function testDatasetNotificationModulesList()
    {
    }

    /**
     * Test case for datasetRegionList
     *
     * .
     *
     */
    public function testDatasetRegionList()
    {
    }

    /**
     * Test case for datasetTemplateList
     *
     * .
     *
     */
    public function testDatasetTemplateList()
    {
    }

    /**
     * Test case for datasetViesCompanyInfoRead
     *
     * .
     *
     */
    public function testDatasetViesCompanyInfoRead()
    {
    }
}
