<?php
/**
 * DocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for documentsDocumentsCreate
     *
     * .
     *
     */
    public function testDocumentsDocumentsCreate()
    {
    }

    /**
     * Test case for documentsDocumentsDelete
     *
     * .
     *
     */
    public function testDocumentsDocumentsDelete()
    {
    }

    /**
     * Test case for documentsDocumentsDocumentsReportPdf
     *
     * .
     *
     */
    public function testDocumentsDocumentsDocumentsReportPdf()
    {
    }

    /**
     * Test case for documentsDocumentsDownloadArchive
     *
     * .
     *
     */
    public function testDocumentsDocumentsDownloadArchive()
    {
    }

    /**
     * Test case for documentsDocumentsList
     *
     * .
     *
     */
    public function testDocumentsDocumentsList()
    {
    }

    /**
     * Test case for documentsDocumentsMarkAs
     *
     * .
     *
     */
    public function testDocumentsDocumentsMarkAs()
    {
    }

    /**
     * Test case for documentsDocumentsPartialUpdate
     *
     * .
     *
     */
    public function testDocumentsDocumentsPartialUpdate()
    {
    }

    /**
     * Test case for documentsDocumentsPdfPagesPreview
     *
     * .
     *
     */
    public function testDocumentsDocumentsPdfPagesPreview()
    {
    }

    /**
     * Test case for documentsDocumentsPdfPagesSplit
     *
     * .
     *
     */
    public function testDocumentsDocumentsPdfPagesSplit()
    {
    }

    /**
     * Test case for documentsDocumentsRead
     *
     * .
     *
     */
    public function testDocumentsDocumentsRead()
    {
    }

    /**
     * Test case for documentsDocumentsUpdate
     *
     * .
     *
     */
    public function testDocumentsDocumentsUpdate()
    {
    }

    /**
     * Test case for documentsEmployeeEmailDelete
     *
     * .
     *
     */
    public function testDocumentsEmployeeEmailDelete()
    {
    }

    /**
     * Test case for documentsEmployeeEmailRead
     *
     * .
     *
     */
    public function testDocumentsEmployeeEmailRead()
    {
    }

    /**
     * Test case for documentsTypesList
     *
     * .
     *
     */
    public function testDocumentsTypesList()
    {
    }
}
