<?php
/**
 * RentalApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BAPP API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.23
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RentalApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RentalApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for rentalCalendarCreate
     *
     * .
     *
     */
    public function testRentalCalendarCreate()
    {
    }

    /**
     * Test case for rentalCalendarDelete
     *
     * .
     *
     */
    public function testRentalCalendarDelete()
    {
    }

    /**
     * Test case for rentalCalendarList
     *
     * .
     *
     */
    public function testRentalCalendarList()
    {
    }

    /**
     * Test case for rentalCalendarPartialUpdate
     *
     * .
     *
     */
    public function testRentalCalendarPartialUpdate()
    {
    }

    /**
     * Test case for rentalCalendarRead
     *
     * .
     *
     */
    public function testRentalCalendarRead()
    {
    }

    /**
     * Test case for rentalCalendarUpdate
     *
     * .
     *
     */
    public function testRentalCalendarUpdate()
    {
    }

    /**
     * Test case for rentalGuestRead
     *
     * .
     *
     */
    public function testRentalGuestRead()
    {
    }

    /**
     * Test case for rentalResourceCreate
     *
     * .
     *
     */
    public function testRentalResourceCreate()
    {
    }

    /**
     * Test case for rentalResourceDelete
     *
     * .
     *
     */
    public function testRentalResourceDelete()
    {
    }

    /**
     * Test case for rentalResourceGroupCreate
     *
     * .
     *
     */
    public function testRentalResourceGroupCreate()
    {
    }

    /**
     * Test case for rentalResourceGroupDelete
     *
     * .
     *
     */
    public function testRentalResourceGroupDelete()
    {
    }

    /**
     * Test case for rentalResourceGroupList
     *
     * .
     *
     */
    public function testRentalResourceGroupList()
    {
    }

    /**
     * Test case for rentalResourceGroupPartialUpdate
     *
     * .
     *
     */
    public function testRentalResourceGroupPartialUpdate()
    {
    }

    /**
     * Test case for rentalResourceGroupRead
     *
     * .
     *
     */
    public function testRentalResourceGroupRead()
    {
    }

    /**
     * Test case for rentalResourceGroupUpdate
     *
     * .
     *
     */
    public function testRentalResourceGroupUpdate()
    {
    }

    /**
     * Test case for rentalResourceList
     *
     * .
     *
     */
    public function testRentalResourceList()
    {
    }

    /**
     * Test case for rentalResourcePartialUpdate
     *
     * .
     *
     */
    public function testRentalResourcePartialUpdate()
    {
    }

    /**
     * Test case for rentalResourceRead
     *
     * .
     *
     */
    public function testRentalResourceRead()
    {
    }

    /**
     * Test case for rentalResourceUpdate
     *
     * .
     *
     */
    public function testRentalResourceUpdate()
    {
    }
}
